name: Deploy valormaster
on:
  push:
    branches: [ main ]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Authenticate to GCP
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}
          create_credentials_file: true
          export_environment_variables: true
      - name: Debug GCP_SA_KEY
        # Print first character of the secret (should be '{')
        run: echo "${{ secrets.GCP_SA_KEY }}" | head -c 1
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT }}
          install_components: |
            beta
            alpha
            artifact-registry
      - name: Build and push Docker image
        run: |
          IMAGE="us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT }}/valormaster-repo/agent:${{ github.sha }}"
          docker build -t $IMAGE -f agent/Dockerfile .
          docker push $IMAGE
      - name: Update Vertex AI Agent
        run: |
          gcloud alpha generative-ai agents update valormaster \
            --region=us-central1 \
            --artifact-staging-bucket=gs://valor-master-agent-staging \
            --image=$IMAGE