name: Deploy ValorMaster
on:
  push:
    branches: [ main ]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          service_account_key: ${{ a44c77589e82fb60ac17dd16a158b996b35873ed }}
          project_id: ${{ valormaster }}
      - name: Install dependencies
        run: |
          pip install --upgrade google-cloud-aiplatform vertexai
      - name: Build and push Docker image
        run: |
          IMAGE="us-central1-docker.pkg.dev/${{ valormaster }}/valor-master-agent-repo/agent:$GITHUB_SHA"
          docker build -t $IMAGE ./agent
          docker push $IMAGE
      - name: Update Vertex AI Agent
        run: |
          gcloud alpha generative-ai agents update ValorMaster \
            --region=us-central1 \
            --artifact-staging-bucket=gs://valor-master-agent-staging \
            --image=$IMAGE
